version: '3'
services:
  db:
    image: mariadb
    container_name: nextcloud-mariadb
    networks:
      - nextcloud_network
    volumes:
      - db:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
    restart: unless-stopped
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      - nextcloud_network
    ports:
      - 9000:80
    depends_on:
      - db
      - redis
    volumes:
    - nextcloud:/var/www/html
    - ./app/config:/var/www/html/config
    - type: bind
      source: ./data
      target: /var/www/html/data
    - ./app/custom_apps:/var/www/html/custom_apps
    - ./app/themes:/var/www/html/themes
    - /etc/localtime:/etc/localtime:ro
    environment:
      - TRUSTED_PROXIES=127.0.0.1
      - PHP_MEMORY_LIMIT=4G
      - PHP_UPLOAD_LIMIT=20G
      - APACHE_BODY_LIMIT=0
      - REDIS_HOST=nextcloud-redis
      - REDIS_HOST_PASSWORD=[PASSWORD HERE]
    restart: unless-stopped
  redis:
    image: redis:latest
    container_name: nextcloud-redis
    networks:
      - nextcloud_network
    command: redis-server --save 20 1 --loglevel warning --requirepass [PASSWORD HERE]
    volumes:
     - $PWD/redis-data:/var/lib/redis
     - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
volumes:
  nextcloud:
  db:
  redis:
networks:
  nextcloud_network: